server:
    port: 9001
spring:
    application:
        name: base #指定服务名
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/geek_base?characterEncoding=utf-8&userSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: true
    profiles:
        active: dev
    config:
        import: optional:configserver:http://root:s3cr3t@localhost:12000
        

    cloud:
        bus:
            enabled: true
        refresh:
            enabled: true
        # config:
        #     discovery:
        #         service-id: config
        #         enabled: true
    kafka:
        bootstrap-servers: 
        - localhost:9092
        
management:
    endpoints:
        web:
            exposure:
                include: '*'
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true
